// <auto-generated />
namespace NTUOC7registration.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class unicode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(unicode));
        
        string IMigrationMetadata.Id
        {
            get { return "201408050519316_unicode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
